#!/usr/bin/perl

# Perl CGI script
use strict;
use warnings;
use CGI;

my $cgi = CGI->new;

print $cgi->header('text/html');

# Get values to avoid complex interpolation in heredoc
my $method = $ENV{REQUEST_METHOD} || 'Not available';
my $query = $ENV{QUERY_STRING} || 'None';
my $content_type = $ENV{CONTENT_TYPE} || 'Not specified';
my $user_agent = $ENV{HTTP_USER_AGENT} || 'Unknown';
my $server = ($ENV{SERVER_NAME} || 'Unknown') . ':' . ($ENV{SERVER_PORT} || 'Unknown');
my $timestamp = scalar localtime;
my $pwd = `pwd`;
chomp $pwd;

print <<"HTML";
<!DOCTYPE html>
<html>
<head>
    <title>Perl CGI Demo</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; background: #f0f8ff; }
        .container { max-width: 600px; margin: 0 auto; }
        .perl-box { background: #e6f3ff; padding: 20px; border-radius: 10px; border: 2px solid #4169e1; }
        .info { background: #fff; padding: 10px; margin: 10px 0; border-left: 4px solid #4169e1; }
        code { background: #f4f4f4; padding: 2px 4px; border-radius: 3px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="perl-box">
            <h1>🐪 Perl CGI Script</h1>
            <p><strong>Language:</strong> Perl</p>
            <p><strong>CGI Module:</strong> CGI.pm</p>
            
            <div class="info">
                <h3>📊 Request Information</h3>
                <p><strong>Method:</strong> $method</p>
                <p><strong>Query String:</strong> $query</p>
                <p><strong>Content Type:</strong> $content_type</p>
                <p><strong>User Agent:</strong> $user_agent</p>
                <p><strong>Server:</strong> $server</p>
            </div>
            
            <div class="info">
                <h3>🕒 Execution Details</h3>
                <p><strong>Timestamp:</strong> $timestamp</p>
                <p><strong>Process ID:</strong> $$</p>
                <p><strong>Working Directory:</strong> $pwd</p>
            </div>
            
            <div class="info">
                <h3>💻 Perl Information</h3>
                <p><strong>Perl Version:</strong> $^V</p>
                <p><strong>Operating System:</strong> $^O</p>
                <p><strong>Executable:</strong> $^X</p>
            </div>
            
            <p><em>This content was generated by a Perl CGI script using CGI.pm</em></p>
        </div>
    </div>
</body>
</html>
HTML
